Repository TEAM-JaChewi/tryit, pull requests merged in 2022-08, with the labels that each got.

#275 feat: 회원 관련 뷰 리팩토링(CSS)
  src/main/resources/static/css/member.css
  src/main/resources/static/css/style.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/members/edit.html
  src/main/resources/templates/members/register.html
Labels: 🛠리팩토링, 😊회원, 🖼디자인

#280 feat: 장바구니에서 수량 변경 시 충분한 재고가 있는지 검증 사항 추가
  src/main/java/shop/tryit/domain/cart/service/CartFacade.java
  src/main/java/shop/tryit/domain/item/entity/Item.java
  src/main/java/shop/tryit/web/cart/CartController.java
  src/main/resources/templates/carts/list.html
Labels: 🛠리팩토링, ✒️기능개발, 🛒장바구니

#279 refactor: 주문 상세 dto 조회 기능 수정
  src/main/java/shop/tryit/domain/item/repository/ItemRepository.java
  src/main/java/shop/tryit/domain/order/dto/OrderDetailSearchDto.java
  src/main/java/shop/tryit/repository/item/ItemCustom.java
  src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
  src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
  src/main/java/shop/tryit/repository/order/OrderCustomImpl.java
  src/main/java/shop/tryit/repository/order/OrderDetailCustomImpl.java
  src/test/java/shop/tryit/domain/item/ItemRepositoryTests.java
Labels: 🛠리팩토링, ✒️기능개발, 📞주문

#285 feat: 주문 퍼사드에 주문 상세 조회 기능 구현
  src/main/java/shop/tryit/domain/item/entity/Item.java
  src/main/java/shop/tryit/domain/order/Order.java
  src/main/java/shop/tryit/domain/order/OrderDetail.java
  src/main/java/shop/tryit/domain/order/dto/OrderFindDto.java
  src/main/java/shop/tryit/domain/order/service/OrderDetailService.java
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
Labels: ✒️기능개발, 📞주문

#282 refactor: 주문 컨트롤러로 데이터 보낸 후 받는 상태코드 변경
  src/main/resources/templates/payment/payment-form.html
Labels: 🛠리팩토링, 💰결제

#288 refactor: 장바구니에서 선택된 상품 없이 주문 요청 시 null 이슈 해결
  src/main/resources/templates/carts/list.html
Labels: 🛠리팩토링, 🛒장바구니

#287 feat: 주문 컨트롤러에서 주문 상세 뷰 기능 구현
  src/main/java/shop/tryit/web/order/OrderController.java
  src/main/resources/templates/orders/detail.html
  src/main/resources/templates/orders/list.html
Labels: 📞주문

#289 feat: 결제 컨트롤러 검증 추가
  src/main/java/shop/tryit/domain/payment/PaymentFacade.java
  src/main/java/shop/tryit/web/payment/PaymentController.java
Labels: ✒️기능개발, 💰결제

#293 refactor: 로그인 폼 리팩토링(CSS)
  src/main/resources/static/css/member.css
  src/main/resources/static/css/style.css
  src/main/resources/templates/members/login-form.html
Labels: 🛠리팩토링, 😊회원, 🖼디자인

#292 refactor: 장바구니에서 상품의 재고보다 많은 수량을 주문할 수 없도록 검증 처리
  src/main/java/shop/tryit/domain/cart/dto/CartListDto.java
  src/main/java/shop/tryit/domain/cart/entity/CartItem.java
  src/main/java/shop/tryit/domain/cart/service/CartFacade.java
  src/main/resources/templates/carts/list.html
Labels: 🛠리팩토링, 🛒장바구니

#294 feat: 주문 컨트롤러에 주문 등록 기능 구현
  src/main/java/shop/tryit/domain/order/dto/OrderDetailDto.java
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
  src/main/java/shop/tryit/web/order/OrderController.java
Labels: ✒️기능개발, 📞주문

#299 refactor: 주문 등록시 장바구니 상품 삭제 기능 구현
  src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
  src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
  src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
Labels: 🛠리팩토링, ✒️기능개발, 📞주문

#301 refactor: 장바구니에서 상품 삭제 버튼 기능 에러 수정
  src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
  src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
  src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
Labels: 🛠리팩토링

#304 refactor: 장바구니 상품 레포지토리에 findByCartAndItem 반환 값을 Optional로 변경
  src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
  src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
Labels: 🛠리팩토링, 🛒장바구니

#307 refactor: 주문 등록시 장바구니 상품 삭제 기능 수정
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
Labels: 🛠리팩토링, 📞주문, 🛒장바구니

#306 refactor: 상품 목록 페이지 디자인 변경
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/resources/static/css/item.css
  src/main/resources/templates/items/list.html
Labels: 🛠리팩토링, 🎁상품, 🖼디자인

#312 refactor: 공지 수정, 삭제 안되는 이슈 해결
  src/main/java/shop/tryit/domain/notice/service/NoticeFacade.java
  src/main/java/shop/tryit/domain/notice/service/NoticeService.java
Labels: 🛠리팩토링, 📋공지사항

#314 refactor: 게시판 수정, 댓글 삭제 기능 이슈 해결
  src/main/java/shop/tryit/web/qna/AnswerController.java
  src/main/java/shop/tryit/web/qna/QuestionController.java
Labels: 🛠리팩토링, 📰게시판

#316 feat: 질문 삭제하기 및 댓글 수정하기 기능 추가
  src/main/java/shop/tryit/domain/qna/entity/Answer.java
  src/main/java/shop/tryit/domain/qna/entity/Question.java
  src/main/java/shop/tryit/domain/qna/service/QnAFacade.java
  src/main/java/shop/tryit/web/qna/AnswerController.java
  src/main/java/shop/tryit/web/qna/QuestionController.java
  src/main/resources/templates/qna/answer-update.html
  src/main/resources/templates/qna/detail-view.html
Labels: ✒️기능개발, 📰게시판

#317 refactor: 상품 도메인 관련 리팩토링
  src/main/java/shop/tryit/domain/cart/service/CartFacade.java
  src/main/java/shop/tryit/domain/item/entity/Item.java
  src/main/java/shop/tryit/domain/item/service/ImageService.java
  src/main/java/shop/tryit/domain/item/service/ImageStore.java
  src/main/java/shop/tryit/domain/item/service/ItemFacade.java
  src/main/java/shop/tryit/domain/item/service/ItemService.java
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
  src/main/java/shop/tryit/domain/payment/service/PaymentFacade.java
  src/main/java/shop/tryit/web/item/ItemController.java
Labels: 🛠리팩토링, 🎁상품

#318 refactor: 시큐리티 경로 보안 설정
  src/main/java/shop/tryit/config/WebSecurityConfig.java
  src/main/java/shop/tryit/domain/member/InitDB.java
  src/main/java/shop/tryit/domain/member/entity/MemberRole.java
  src/main/java/shop/tryit/domain/member/service/MemberFacade.java
  src/main/java/shop/tryit/domain/member/service/MemberSecurityService.java
  src/main/java/shop/tryit/domain/qna/service/QnAFacade.java
  src/main/java/shop/tryit/web/qna/QuestionController.java
Labels: 🛠리팩토링, 🔐시큐리티

#321 refactor: ADMIN 권한일 경우 경로 보안 위치 변경
  src/main/java/shop/tryit/config/WebSecurityConfig.java
Labels: 🛠리팩토링, 🔐시큐리티

#324 refactor: 리다이렉트 이슈로 인한 관리자 보안 경로 수정
  src/main/java/shop/tryit/config/WebSecurityConfig.java
Labels: 🛠리팩토링, 🔐시큐리티

#325 refactor: 회원 수정 관련 명칭 변경
  src/main/java/shop/tryit/web/member/MemberController.java
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/members/update.html
Labels: 🛠리팩토링, 😊회원, 🖼디자인

#329 refactor: 회원 관련 웹 리팩토링
  src/main/resources/templates/members/login-form.html
  src/main/resources/templates/members/register.html
Labels: 🛠리팩토링, 😊회원, 🖼디자인

#331 feat: 공지에 css 적용
  src/main/resources/static/css/notice.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/notices/detail.html
  src/main/resources/templates/notices/list.html
  src/main/resources/templates/notices/register.html
  src/main/resources/templates/notices/update.html
Labels: ✒️기능개발, 🖼디자인, 📋공지사항

#333 feat: 질문 게시판 페이지 디자인 변경
  src/main/resources/static/css/qna.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/qna/answer-update.html
  src/main/resources/templates/qna/check-password.html
  src/main/resources/templates/qna/detail-view.html
  src/main/resources/templates/qna/list.html
  src/main/resources/templates/qna/register.html
  src/main/resources/templates/qna/update.html
Labels: ✒️기능개발, 📰게시판

#336 refactor: 결제 폼에 적용된 css 변경 및 포맷팅
  src/main/resources/static/css/style.css
  src/main/resources/templates/payment/payment-form.html
Labels: 🛠리팩토링, 🖼디자인, 🎆스타일, 💰결제

#337 feat: 주문 페이지에 디자인 적용하기
  src/main/java/shop/tryit/domain/order/dto/OrderFindDto.java
  src/main/java/shop/tryit/domain/order/entity/Order.java
  src/main/java/shop/tryit/domain/order/entity/OrderDetail.java
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
  src/main/java/shop/tryit/web/order/OrderController.java
  src/main/resources/static/css/order.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/orders/detail.html
  src/main/resources/templates/orders/list.html
Labels: 🛠리팩토링, 📞주문, 🖼디자인, 🎆스타일

#338 refactor: 상품 페이지 디자인 변경
  src/main/resources/static/css/cart.css
  src/main/resources/static/css/common.css
  src/main/resources/static/css/item.css
  src/main/resources/templates/items/detail.html
  src/main/resources/templates/items/register.html
  src/main/resources/templates/items/update.html
Labels: 🛠리팩토링, 🎁상품, 🖼디자인

#341 build: db 변경
  build.gradle
  src/main/resources/application.yml
Labels: ⚙세팅

#343 feat: 공지사항 수정 시 검증 기능 추가
  src/main/java/shop/tryit/web/notice/NoticeController.java
Labels: ✒️기능개발, 📋공지사항

#345 refactor: 본인 및 관리자 제외시 게시글 수정 막기 기능 추가
  src/main/java/shop/tryit/web/qna/QuestionController.java
Labels: 🛠리팩토링, 📰게시판

#346 refactor: 전반적인 css 정리
  src/main/resources/static/css/cart.css
  src/main/resources/static/css/common.css
  src/main/resources/static/css/item.css
  src/main/resources/static/css/member.css
  src/main/resources/static/css/notice.css
  src/main/resources/static/css/order.css
  src/main/resources/static/css/qna.css
  src/main/resources/static/css/style.css
  src/main/resources/templates/carts/list.html
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/items/detail.html
  src/main/resources/templates/items/list.html
  src/main/resources/templates/members/login-form.html
  src/main/resources/templates/members/register.html
  src/main/resources/templates/members/update.html
  src/main/resources/templates/notices/detail.html
  src/main/resources/templates/notices/list.html
  src/main/resources/templates/notices/register.html
  src/main/resources/templates/notices/update.html
  src/main/resources/templates/orders/detail.html
  src/main/resources/templates/orders/list.html
  src/main/resources/templates/payment/payment-form.html
  src/main/resources/templates/qna/detail-view.html
  src/main/resources/templates/qna/list.html
  src/main/resources/templates/qna/register.html
Labels: 🛠리팩토링, 🖼디자인

#349 feat: 댓글 기능 버튼을 관리자만 보이도록 설정
  src/main/java/shop/tryit/web/qna/AnswerController.java
  src/main/resources/static/css/qna.css
  src/main/resources/templates/qna/answer-update.html
  src/main/resources/templates/qna/detail-view.html
Labels: ✒️기능개발, 📰게시판

#352 refactor: 시큐리티 보안 경로 수정
  src/main/java/shop/tryit/config/WebSecurityConfig.java
Labels: 🛠리팩토링, 🔐시큐리티

#353 build: InitDB 삭제 및 DDL create 속성삭제
  src/main/java/shop/tryit/domain/member/InitDB.java
  src/main/resources/application.yml
Labels: ⚙세팅

#355 refactor: 시큐리티 config 수정 및 장바구니 퍼사드 @Transactional 추가
  src/main/java/shop/tryit/config/WebSecurityConfig.java
  src/main/java/shop/tryit/domain/cart/service/CartFacade.java
  src/main/java/shop/tryit/domain/member/service/MemberSecurityService.java
Labels: 🐛버그, 🛠리팩토링, 🔐시큐리티, 🛒장바구니

#358 refactor: QnA / 공지 페이징 사이즈 개수 변경
  src/main/java/shop/tryit/domain/notice/service/NoticeService.java
  src/main/java/shop/tryit/domain/qna/service/AnswerService.java
  src/main/java/shop/tryit/web/qna/QuestionController.java
Labels: 🛠리팩토링, 📰게시판, 📋공지사항

#356 feat: 게시글 기능 관련 버튼을 작성자 또는 관리자한테만 보이도록 설정
  src/main/java/shop/tryit/domain/qna/service/QnAFacade.java
  src/main/java/shop/tryit/web/qna/QuestionController.java
  src/main/resources/templates/qna/detail-view.html
Labels: 🛠리팩토링, ✒️기능개발, 📰게시판

#360 refactor: aws s3 적용
  build.gradle
  src/main/java/shop/tryit/TryitApplication.java
  src/main/java/shop/tryit/domain/item/dto/ItemResponseDto.java
  src/main/java/shop/tryit/domain/item/dto/ItemSearchDto.java
  src/main/java/shop/tryit/domain/item/service/ImageService.java
  src/main/java/shop/tryit/domain/item/service/ImageStore.java
  src/main/java/shop/tryit/domain/item/service/ItemFacade.java
  src/main/java/shop/tryit/domain/item/service/S3Service.java
  src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
  src/main/java/shop/tryit/web/item/ImageController.java
  src/main/resources/application.yml
  src/main/resources/templates/items/detail.html
  src/main/resources/templates/items/list.html
Labels: 🛠리팩토링, ✒️기능개발, 🎁상품, ⚙세팅

#362 refactor: 주문, 장바구니, 결제 뷰에서 s3로 이미지 조회
  src/main/java/shop/tryit/domain/cart/dto/CartListDto.java
  src/main/java/shop/tryit/domain/cart/service/CartFacade.java
  src/main/java/shop/tryit/domain/order/dto/OrderFindDto.java
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
  src/main/java/shop/tryit/domain/payment/dto/PaymentResponseDto.java
  src/main/java/shop/tryit/domain/payment/service/PaymentFacade.java
  src/main/resources/templates/carts/list.html
  src/main/resources/templates/orders/detail.html
  src/main/resources/templates/payment/payment-form.html
Labels: 🛠리팩토링, 📞주문, 🛒장바구니, 💰결제

#364 refactor: aws s3 삭제 및 수정 적용
  src/main/java/shop/tryit/domain/item/dto/ItemResponseDto.java
  src/main/java/shop/tryit/domain/item/service/ImageService.java
  src/main/java/shop/tryit/domain/item/service/ImageStore.java
  src/main/java/shop/tryit/domain/item/service/ItemFacade.java
  src/main/resources/templates/items/detail.html
Labels: 🛠리팩토링, 🎁상품, 🎆스타일

#366 Build: yml 파일 gitignore 적용
  .gitignore
  src/main/resources/application-security.yml
  src/main/resources/application.yml
Labels: ⚙세팅

#368 build: yml 파일 gitignore 재적용
  src/main/resources/application-security.yml
Labels: ⚙세팅

#370 refactor: 상품 상세 뷰에 상품 이미지 크기 조절
  src/main/resources/static/css/item.css
  src/main/resources/templates/items/detail.html
Labels: 🛠리팩토링, 🎁상품, 🖼디자인

#372 feat: 공지사항에 관리자만 공지 관련 기능 버튼이 보이도록 설정
  src/main/resources/templates/notices/detail.html
  src/main/resources/templates/notices/register.html
  src/main/resources/templates/notices/update.html
Labels: ✒️기능개발, 📋공지사항

#374 refactor: QnA 답글 등록 시 검증 메시지가 뜰 때 기존 답변들이 보이지 않는 이슈 해결
  src/main/java/shop/tryit/web/qna/AnswerController.java
Labels: 🛠리팩토링, 📰게시판

#376 refactor: QnA 비밀번호 체크 폼의 디자인 변경 및 검증 메세지가 나오지 않는 이슈 해결
  src/main/java/shop/tryit/web/qna/QuestionController.java
  src/main/resources/static/css/qna.css
  src/main/resources/templates/qna/answer-update.html
  src/main/resources/templates/qna/check-password.html
Labels: 🛠리팩토링, 📰게시판

#378 refactor: 지정된 경로가 없을 시 해당 경로 생성 기능 추가
  src/main/java/shop/tryit/domain/item/service/ImageStore.java
Labels: 🛠리팩토링, 🎁상품

#382 refactor: thymeleaf 이슈(Error resolving template) 해결
  src/main/java/shop/tryit/web/cart/CartController.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/member/MemberController.java
  src/main/java/shop/tryit/web/order/OrderController.java
  src/main/java/shop/tryit/web/payment/PaymentController.java
  src/main/java/shop/tryit/web/qna/AnswerController.java
  src/test/java/shop/tryit/domain/item/ItemServiceTests.java
Labels: 🐛버그, 🛠리팩토링, 😊회원, 🎁상품, 📞주문, 📰게시판, 🛒장바구니, 💰결제

#383 refactor: 주문 등록시 location url 주소 수정
  src/main/java/shop/tryit/web/order/OrderController.java
Labels: 🛠리팩토링, 📞주문

#385 refactor: QnA에서 질문 게시글의 페이징 사이즈 수정
  src/main/java/shop/tryit/domain/qna/service/QnAFacade.java
Labels: 🛠리팩토링, 📰게시판

#386 v1.0.3 : 배포
  src/main/java/shop/tryit/domain/qna/service/QnAFacade.java
  src/main/java/shop/tryit/web/cart/CartController.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/member/MemberController.java
  src/main/java/shop/tryit/web/order/OrderController.java
  src/main/java/shop/tryit/web/payment/PaymentController.java
  src/main/java/shop/tryit/web/qna/AnswerController.java
  src/test/java/shop/tryit/domain/item/ItemServiceTests.java
Labels: 📢 배포

#388 refactor: 인증되지 않은 사용자가 장바구니 담기 버튼을 누를 경우 로그인을 유도하는 알럿이 뜨도록 변경
  src/main/java/shop/tryit/config/WebSecurityConfig.java
  src/main/resources/static/vendor/php-email-form/validate.js
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/items/detail.html
Labels: 🛠리팩토링, 🛒장바구니
