Repository TEAM-JaChewi/tryit, pull requests merged in 2022-06, with the labels that each got.

#16 refactor: 회원 레포지토리 패키지명 변경
  src/main/java/shop/tryit/repository/member/MemberJpaRepository.java
  src/main/java/shop/tryit/repository/member/MemberRepositoryImpl.java
  src/test/java/shop/tryit/repository/member/MemberRepositoryImplTests.java
Labels: 🛠리팩토링, 😊회원

#19 feat: QnA 게시판 엔티티 생성
  src/main/java/shop/tryit/domain/answer/Answer.java
  src/main/java/shop/tryit/domain/question/Question.java
Labels: ✨기능개발

#23 refector: 상품 관련 엔티티 연관관계 수정
  src/main/java/shop/tryit/domain/item/Item.java
  src/main/java/shop/tryit/domain/item/ItemImage.java
Labels: 🛠리팩토링, 🎁상품

#25 Feat: 초기 Spring Security 설정 및 회원 서비스 생성
  build.gradle
  src/main/java/shop/tryit/WebSecurityConfig.java
  src/main/java/shop/tryit/domain/member/Member.java
  src/main/java/shop/tryit/domain/member/MemberFormDto.java
  src/main/java/shop/tryit/domain/member/MemberService.java
  src/test/java/shop/tryit/PasswordEncoderTest.java
  src/test/java/shop/tryit/domain/member/MemberServiceTests.java
Labels: ✨기능개발, 😊회원, 👨‍💻시큐리티

#29 feat: 상품 레포지토리 생성 및 테스트
  src/main/java/shop/tryit/domain/item/ItemRepository.java
  src/main/java/shop/tryit/repository/item/ItemJpaRepository.java
  src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
  src/test/java/shop/tryit/domain/item/ItemRepositoryTests.java
Labels: ✨기능개발, 🎁상품

#31 feat: 상품 등록 기능 개발 및 테스트
  src/main/java/shop/tryit/domain/item/ItemService.java
  src/test/java/shop/tryit/domain/item/ItemServiceTests.java
Labels: ✨기능개발, 🎁상품

#35 feat: 게시판 조회 기능 구현
  src/main/java/shop/tryit/domain/question/QuestionRepository.java
  src/main/java/shop/tryit/domain/question/QuestionService.java
  src/main/java/shop/tryit/repository/question/QuestionRepositoryImpl.java
Labels: ✨기능개발

#36 feat: 답변 저장 기능 구현
  src/main/java/shop/tryit/domain/answer/Answer.java
  src/main/java/shop/tryit/domain/answer/AnswerRepository.java
  src/main/java/shop/tryit/domain/answer/AnswerService.java
  src/main/java/shop/tryit/repository/answer/AnswerJpaRepository.java
  src/main/java/shop/tryit/repository/answer/AnswerRepositoryImpl.java
  src/test/java/shop/tryit/domain/answer/AnswerServiceTests.java
Labels: ✨기능개발

#38 게시판 수정 기능 구현
  src/main/java/shop/tryit/domain/question/QuestionService.java
  src/test/java/shop/tryit/domain/question/QuestionServiceTests.java
Labels: ✨기능개발, 📰게시판

#42 refactor: 시큐리티 권한 추가 및 헤더 타임리프,css 적용
  src/main/java/shop/tryit/WebSecurityConfig.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/fragments/bodyHeader.html
  src/main/resources/templates/fragments/header.html
Labels: 🖼UI, 👨‍💻시큐리티

#40 feat : 답변 수정 기능 구현
  src/main/java/shop/tryit/domain/answer/AnswerRepository.java
  src/main/java/shop/tryit/domain/answer/AnswerService.java
  src/main/java/shop/tryit/repository/answer/AnswerRepositoryImpl.java
  src/test/java/shop/tryit/domain/answer/AnswerServiceTests.java
Labels: ✨기능개발, 📰게시판

#45 feat: 게시판 삭제 기능 구현
  src/main/java/shop/tryit/domain/answer/AnswerRepository.java
  src/main/java/shop/tryit/domain/question/QuestionRepository.java
  src/main/java/shop/tryit/domain/question/QuestionService.java
  src/main/java/shop/tryit/repository/answer/AnswerJpaRepository.java
  src/main/java/shop/tryit/repository/answer/AnswerRepositoryImpl.java
  src/main/java/shop/tryit/repository/question/QuestionRepositoryImpl.java
  src/test/java/shop/tryit/domain/question/QuestionServiceTests.java
Labels: ✨기능개발, 📰게시판

#48 feat: 상품 등록 웹 계층 개발
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/item/ItemFormDto.java
  src/main/resources/templates/items/register.html
Labels: ✨기능개발, 🎁상품

#49 feat: 회원가입 기능 구현
  src/main/java/shop/tryit/domain/common/Address.java
  src/main/java/shop/tryit/domain/member/Member.java
  src/main/java/shop/tryit/domain/member/MemberFormDto.java
  src/main/java/shop/tryit/domain/member/MemberRepository.java
  src/main/java/shop/tryit/domain/member/MemberService.java
  src/main/java/shop/tryit/repository/member/MemberRepositoryImpl.java
  src/main/java/shop/tryit/web/member/MemberAdapter.java
  src/main/java/shop/tryit/web/member/MemberController.java
  src/main/java/shop/tryit/web/member/MemberFormDto.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/members/register.html
  src/test/java/shop/tryit/domain/member/MemberServiceTests.java
Labels: ✨기능개발, 😊회원, 🖼UI

#51 feat: 상품 이미지 파일 업로드 기능 구현
  src/main/java/shop/tryit/domain/item/Item.java
  src/main/java/shop/tryit/domain/item/ItemFile.java
  src/main/java/shop/tryit/domain/item/ItemFileStore.java
  src/main/resources/application.yml
Labels: ✨기능개발, 🎁상품

#54 refactor: 상품 카테고리 enum 타입으로 변경
  src/main/java/shop/tryit/domain/item/Category.java
  src/main/java/shop/tryit/domain/item/Item.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/resources/templates/items/register.html
Labels: 🛠리팩토링, 🎁상품

#56 refactor: 회원 등록 DTO 어노테이션 적용
  src/main/java/shop/tryit/web/member/MemberFormDto.java
  src/main/resources/templates/members/register.html
Labels: 🛠리팩토링, 😊회원

#61 refactor: 파일 업로드 경로 관련 수정
  src/main/java/shop/tryit/domain/item/ItemFileStore.java
  src/main/resources/application.yml
Labels: 🛠리팩토링, 🎁상품

#62 feat: 로그인/로그아웃 기능 구현 및 시큐리티 작업
  src/main/java/shop/tryit/WebSecurityConfig.java
  src/main/java/shop/tryit/domain/member/MemberRepository.java
  src/main/java/shop/tryit/domain/member/MemberRole.java
  src/main/java/shop/tryit/domain/member/MemberSecurityService.java
  src/main/java/shop/tryit/repository/member/MemberJpaRepository.java
  src/main/java/shop/tryit/repository/member/MemberRepositoryImpl.java
  src/main/java/shop/tryit/web/member/MemberAdapter.java
  src/main/java/shop/tryit/web/member/MemberController.java
  src/main/java/shop/tryit/web/member/MemberFormDto.java
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/members/login-form.html
Labels: ✨기능개발, 😊회원, 👨‍💻시큐리티

#67 refactor: 회원 이메일을 통해 회원 찾기
  src/main/java/shop/tryit/domain/member/MemberService.java
  src/test/java/shop/tryit/domain/member/MemberServiceTests.java
Labels: 🛠리팩토링, 😊회원

#68 feat: 상품 목록 기능 개발 및 테스트
  src/main/java/shop/tryit/domain/item/ItemService.java
  src/test/java/shop/tryit/domain/item/ItemServiceTests.java
Labels: ✨기능개발, 🎁상품

#72 refactor: body-header 타임리프 수정
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/items/register.html
  src/main/resources/templates/members/login-form.html
  src/main/resources/templates/members/register.html
  src/main/resources/templates/questions/register.html
Labels: 🛠리팩토링, 🖼UI

#70 feat: 답변 삭제 기능 구현
  src/main/java/shop/tryit/domain/answer/AnswerService.java
  src/test/java/shop/tryit/domain/answer/AnswerServiceTests.java
Labels: ✨기능개발, 📰게시판

#76 feat: querydsl 설정 추가
  build.gradle
  src/main/java/shop/tryit/config/QuerydslConfig.java
  src/main/resources/application.yml
Labels: ✨기능개발

#77 refactor: 상품 파일 엔티티 구조 변경
  src/main/java/shop/tryit/domain/item/Item.java
  src/main/java/shop/tryit/domain/item/ItemFile.java
  src/main/java/shop/tryit/domain/item/ItemFileStore.java
  src/main/java/shop/tryit/domain/item/ItemFileType.java
  src/main/java/shop/tryit/web/item/ItemAdapter.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/item/ItemFormDto.java
  src/main/resources/templates/items/register.html
Labels: 🛠리팩토링, 🎁상품

#78 feat: 회원 정보 수정 기능 구현
  src/main/java/shop/tryit/domain/member/Member.java
  src/main/java/shop/tryit/domain/member/MemberService.java
  src/main/java/shop/tryit/web/member/AddressAdapter.java
  src/main/java/shop/tryit/web/member/MemberAdapter.java
  src/main/java/shop/tryit/web/member/MemberController.java
  src/main/resources/templates/members/edit.html
Labels: ✨기능개발, 😊회원, 🖼UI
