Repository TEAM-JaChewi/tryit, pull requests merged in 2022-07, with the labels that each got.

#82 feat: 상품 목록 웹 계층 개발
  src/main/java/shop/tryit/domain/item/ItemFileService.java
  src/main/java/shop/tryit/domain/item/ItemFileStore.java
  src/main/java/shop/tryit/web/item/ItemAdapter.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/item/ItemFileController.java
  src/main/java/shop/tryit/web/item/ItemListDto.java
  src/main/resources/templates/items/list.html
Labels: 🛠리팩토링, ✨기능개발, 🎁상품

#81 feat: 질문 리포지토리의 페이징 기능 구현
  src/main/java/shop/tryit/domain/question/QuestionRepository.java
  src/main/java/shop/tryit/domain/question/QuestionSearchCondition.java
  src/main/java/shop/tryit/domain/question/QuestionSearchDto.java
  src/main/java/shop/tryit/repository/question/QuestionCustom.java
  src/main/java/shop/tryit/repository/question/QuestionCustomImpl.java
  src/main/java/shop/tryit/repository/question/QuestionJpaRepository.java
  src/main/java/shop/tryit/repository/question/QuestionRepositoryImpl.java
  src/test/java/shop/tryit/repository/question/QuestionRepositoryImplTests.java
  src/test/resources/application.yml
Labels: ✨기능개발, 📰게시판

#85 refactor: 상품 이미지 파일 관련 리팩토링
  src/main/java/shop/tryit/domain/item/Image.java
  src/main/java/shop/tryit/domain/item/ImageService.java
  src/main/java/shop/tryit/domain/item/ImageStore.java
  src/main/java/shop/tryit/domain/item/ImageType.java
  src/main/java/shop/tryit/domain/item/Item.java
  src/main/java/shop/tryit/domain/item/ItemFileService.java
  src/main/java/shop/tryit/web/item/ItemAdapter.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/item/ItemFileController.java
  src/main/java/shop/tryit/web/item/ItemListDto.java
Labels: 🛠리팩토링, 🎁상품

#89 feat: 질문 검색 기능 페이징 컨트롤 구현
  src/main/java/shop/tryit/domain/question/QuestionSearchCondition.java
  src/main/java/shop/tryit/domain/question/QuestionSearchDto.java
  src/main/java/shop/tryit/domain/question/QuestionService.java
  src/main/java/shop/tryit/repository/question/QuestionCustomImpl.java
  src/main/java/shop/tryit/web/question/QuestionController.java
  src/main/resources/templates/questions/list.html
  src/test/java/shop/tryit/domain/question/QuestionServiceTests.java
Labels: ✨기능개발, 📰게시판

#93 feat: 상품 수정 개발
  src/main/java/shop/tryit/domain/item/Image.java
  src/main/java/shop/tryit/domain/item/ImageService.java
  src/main/java/shop/tryit/domain/item/ImageStore.java
  src/main/java/shop/tryit/domain/item/ItemService.java
  src/main/java/shop/tryit/web/item/ItemAdapter.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/item/ItemUpdateDto.java
  src/main/resources/templates/items/update.html
Labels: 🛠리팩토링, ✨기능개발, 🎁상품

#92 refactor: 회원가입 검증 애노테이션 추가 및 네비게이션 경로 수정
  src/main/java/shop/tryit/web/member/MemberFormDto.java
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/members/register.html
Labels: 🛠리팩토링, 😊회원, 🖼UI

#97 refactor: 회원 관련 리팩토링
  src/main/java/shop/tryit/domain/member/InitDB.java
  src/main/java/shop/tryit/domain/member/MemberRole.java
  src/main/java/shop/tryit/domain/member/MemberSecurityService.java
  src/main/java/shop/tryit/domain/member/MemberService.java
  src/main/java/shop/tryit/web/member/MemberController.java
Labels: 🛠리팩토링, 😊회원

#96 refactor: 상품 관련 리팩토링
  src/main/java/shop/tryit/domain/item/ImageService.java
  src/main/java/shop/tryit/domain/item/ImageStore.java
  src/main/java/shop/tryit/web/item/ImageController.java
  src/main/java/shop/tryit/web/item/ItemAdapter.java
  src/main/java/shop/tryit/web/item/ItemController.java
Labels: 🛠리팩토링, 🎁상품

#100 feat: 주소 관련 엔티티 클래스 생성
  src/main/java/shop/tryit/domain/member/Member.java
  src/main/java/shop/tryit/domain/order/Order.java
  src/main/java/shop/tryit/domain/order/OrderDetail.java
  src/main/java/shop/tryit/domain/order/OrderStatus.java
Labels: ✨기능개발, 📞주문

#102 feat: 상품 상세 웹 계층 개발
  src/main/java/shop/tryit/web/item/ItemAdapter.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/item/ItemDto.java
  src/main/java/shop/tryit/web/item/ItemListDto.java
  src/main/resources/static/css/style.css
  src/main/resources/static/img/icon/add-to-cart-black.png
  src/main/resources/templates/items/detail.html
  src/main/resources/templates/items/list.html
  src/main/resources/templates/items/register.html
  src/main/resources/templates/items/update.html
Labels: 🛠리팩토링, ✨기능개발, 🎁상품

#108 feat: 상품 검증 사항 적용
  src/main/java/shop/tryit/domain/item/ImageStore.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/item/ItemDto.java
  src/main/java/shop/tryit/web/item/ItemFormDto.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/items/register.html
  src/main/resources/templates/items/update.html
Labels: ✨기능개발, 🎁상품

#106 feat: 답변 등록 기능 구현
  src/main/java/shop/tryit/web/answer/AnswerAdapter.java
  src/main/java/shop/tryit/web/answer/AnswerController.java
  src/main/java/shop/tryit/web/answer/AnswerFormDto.java
Labels: ✨기능개발, 📰게시판

#111 refactor: font css 변경
  src/main/resources/static/css/style.css
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
Labels: 🛠리팩토링, 🖼UI

#109 feat: 주문 관련 레파지토리 생성 및 주문 관련 엔티티 리팩토링
  src/main/java/shop/tryit/domain/order/Order.java
  src/main/java/shop/tryit/domain/order/OrderDetail.java
  src/main/java/shop/tryit/domain/order/OrderDetailRepository.java
  src/main/java/shop/tryit/domain/order/OrderRepository.java
  src/main/java/shop/tryit/repository/order/OrderDetailJpaRepository.java
  src/main/java/shop/tryit/repository/order/OrderDetailRepositoryImpl.java
  src/main/java/shop/tryit/repository/order/OrderJpaRepository.java
  src/main/java/shop/tryit/repository/order/OrderRepositoryImpl.java
Labels: ✨기능개발, 📞주문

#113 feat: 게시판 세부 조회 기능 구현
  src/main/java/shop/tryit/domain/answer/AnswerRepository.java
  src/main/java/shop/tryit/domain/answer/AnswerService.java
  src/main/java/shop/tryit/repository/answer/AnswerJpaRepository.java
  src/main/java/shop/tryit/repository/answer/AnswerRepositoryImpl.java
  src/main/java/shop/tryit/web/answer/AnswerAdapter.java
  src/main/java/shop/tryit/web/answer/AnswerController.java
  src/main/java/shop/tryit/web/answer/AnswerFormDto.java
  src/main/java/shop/tryit/web/question/QuestionAdapter.java
  src/main/java/shop/tryit/web/question/QuestionController.java
  src/main/java/shop/tryit/web/question/QuestionFormDto.java
  src/main/resources/templates/questions/detail-view.html
  src/test/java/shop/tryit/domain/answer/AnswerServiceTests.java
Labels: ✨기능개발, 📰게시판

#114 feat: 상품 삭제 기능 개발
  src/main/java/shop/tryit/domain/item/ImageService.java
  src/main/java/shop/tryit/domain/item/ItemRepository.java
  src/main/java/shop/tryit/domain/item/ItemService.java
  src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/items/detail.html
  src/test/java/shop/tryit/domain/item/ItemServiceTests.java
Labels: ✨기능개발, 🎁상품

#116 build: spring dev tools 의존성 관계 추가
  build.gradle
Labels: ⚙세팅

#119 feat: 페이징 번호 구하는 페이지 클래스 구현
  src/main/java/shop/tryit/domain/common/Pages.java
  src/main/java/shop/tryit/web/question/QuestionController.java
  src/main/resources/templates/questions/detail-view.html
  src/main/resources/templates/questions/list.html
Labels: ✨기능개발

#121 feat: 게시판 수정 기능 구현
  src/main/java/shop/tryit/web/question/QuestionAdapter.java
  src/main/java/shop/tryit/web/question/QuestionController.java
  src/main/java/shop/tryit/web/question/QuestionFormDto.java
  src/main/resources/templates/questions/detail-view.html
  src/main/resources/templates/questions/update.html
Labels: ✨기능개발, 📰게시판

#122 feat: 주문 관련 서비스 구현(단건 주문 서비스)
  src/main/java/shop/tryit/domain/item/Item.java
  src/main/java/shop/tryit/domain/item/NotEnoughStockException.java
  src/main/java/shop/tryit/domain/order/Order.java
  src/main/java/shop/tryit/domain/order/OrderDetail.java
  src/main/java/shop/tryit/domain/order/OrderService.java
  src/test/java/shop/tryit/domain/order/OrderServiceTests.java
Labels: ✨기능개발, 📞주문

#123 feat: 상품 목록 검색, 페이징 처리
  src/main/java/shop/tryit/domain/item/Image.java
  src/main/java/shop/tryit/domain/item/ItemRepository.java
  src/main/java/shop/tryit/domain/item/ItemSearchCondition.java
  src/main/java/shop/tryit/domain/item/ItemService.java
  src/main/java/shop/tryit/repository/item/ItemCustom.java
  src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
  src/main/java/shop/tryit/repository/item/ItemJpaRepository.java
  src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
  src/main/java/shop/tryit/web/item/ItemAdapter.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/item/ItemSearchDto.java
  src/test/java/shop/tryit/domain/item/ItemServiceTests.java
Labels: 🛠리팩토링, ✨기능개발, 🎁상품

#127 refactor: QItemListDTO -> QItemSearchDto 로 클래스명 변경
  src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
Labels: 🛠리팩토링, 🎁상품

#129 feat: 상품 목록 검색, 페이징 웹 계층 개발
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/items/list.html
Labels: ✨기능개발, 🎁상품, 🖼UI

#131 refactor: 상품 관련 리팩토링
  src/main/java/shop/tryit/domain/item/ItemRepository.java
  src/main/java/shop/tryit/domain/item/ItemSearchDto.java
  src/main/java/shop/tryit/domain/item/ItemService.java
  src/main/java/shop/tryit/repository/item/ItemCustom.java
  src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
  src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
  src/main/java/shop/tryit/web/item/ItemAdapter.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/items/detail.html
  src/main/resources/templates/items/list.html
  src/main/resources/templates/items/register.html
  src/main/resources/templates/items/update.html
  src/test/java/shop/tryit/domain/item/ItemServiceTests.java
Labels: 🛠리팩토링, 🎁상품

#133 feat: 사용자 권한에 따른 상품 뷰 처리
  src/main/resources/templates/items/detail.html
  src/main/resources/templates/items/list.html
Labels: ✨기능개발, 🎁상품

#135 feat: 댓글 삭제 처리 구현
  src/main/java/shop/tryit/domain/answer/Answer.java
  src/main/java/shop/tryit/domain/answer/AnswerService.java
  src/main/java/shop/tryit/web/answer/AnswerController.java
  src/main/resources/templates/questions/detail-view.html
Labels: ✨기능개발, 📰게시판

#137 refactor: 상품 재고 update 이슈 해결
  src/main/java/shop/tryit/domain/item/Item.java
Labels: 🛠리팩토링, 🎁상품

#139 feat: 공지 게시판 엔티티 구현
  src/main/java/shop/tryit/domain/notice/Notice.java
  src/main/java/shop/tryit/domain/notice/NoticeRepository.java
  src/main/java/shop/tryit/repository/notice/NoticeJpaRepository.java
  src/main/java/shop/tryit/repository/notice/NoticeRepositoryImpl.java
Labels: ✨기능개발, ⁉ 공지사항

#141 feat: 공지 서비스의 CRUD 기능 구현
  src/main/java/shop/tryit/domain/notice/NoticeService.java
  src/test/java/shop/tryit/domain/notice/NoticeServiceTests.java
Labels: ✨기능개발, ⁉ 공지사항

#143 feat: 공지 컨트롤러의 등록 및 단건 조회 기능 구현
  src/main/java/shop/tryit/web/notice/NoticeAdapter.java
  src/main/java/shop/tryit/web/notice/NoticeController.java
  src/main/java/shop/tryit/web/notice/NoticeSaveFormDto.java
  src/main/java/shop/tryit/web/notice/NoticeViewFormDto.java
  src/main/resources/templates/notices/detail.html
  src/main/resources/templates/notices/register.html
Labels: ✨기능개발, ⁉ 공지사항

#149 feat: 공지 컨트롤러의 수정 기능 구현
  src/main/java/shop/tryit/web/notice/NoticeAdapter.java
  src/main/java/shop/tryit/web/notice/NoticeController.java
  src/main/java/shop/tryit/web/notice/NoticeUpdateFormDto.java
  src/main/resources/templates/notices/update.html
Labels: ✨기능개발, ⁉공지사항

#147 feat: 공지 컨트롤러의 삭제 기능 구현
  src/main/java/shop/tryit/web/notice/NoticeController.java
  src/main/resources/templates/notices/detail.html
Labels: ✨기능개발, 📋공지사항

#151 refactor: QItemSearchDto를 domain 계층으로 이동
  src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
Labels: 🛠리팩토링, 🎁상품

#152 feat: 단건 주문 관련 웹 계층 구현
  src/main/java/shop/tryit/domain/order/OrderDetail.java
  src/main/java/shop/tryit/domain/order/OrderDetailRepository.java
  src/main/java/shop/tryit/domain/order/OrderRepository.java
  src/main/java/shop/tryit/domain/order/OrderService.java
  src/main/java/shop/tryit/repository/order/OrderDetailRepositoryImpl.java
  src/main/java/shop/tryit/repository/order/OrderJpaRepository.java
  src/main/java/shop/tryit/repository/order/OrderRepositoryImpl.java
  src/main/java/shop/tryit/web/order/OrderAdapter.java
  src/main/java/shop/tryit/web/order/OrderController.java
  src/main/java/shop/tryit/web/order/OrderDto.java
  src/main/java/shop/tryit/web/order/OrderFormDto.java
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/orders/list.html
  src/test/java/shop/tryit/domain/order/OrderServiceTests.java
Labels: ✨기능개발, 📞주문

#157 feat: 상품 상세 폼에서 단건 주문 처리
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/order/OrderController.java
  src/main/java/shop/tryit/web/order/OrderFormDto.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/items/detail.html
Labels: 🛠리팩토링, ✨기능개발, 🎁상품, 📞주문

#160 feat: 공지 목록 보기 기능 구현
  src/main/java/shop/tryit/domain/notice/NoticeRepository.java
  src/main/java/shop/tryit/domain/notice/NoticeService.java
  src/main/java/shop/tryit/repository/notice/NoticeRepositoryImpl.java
  src/main/java/shop/tryit/web/notice/NoticeAdapter.java
  src/main/java/shop/tryit/web/notice/NoticeController.java
  src/main/java/shop/tryit/web/notice/NoticeSearchFormDto.java
  src/main/resources/templates/notices/list.html
Labels: ✨기능개발, 📋공지사항

#163 refactor: 스타일 리팩토링
  src/main/resources/static/css/style.css
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/index.html
  src/main/resources/templates/items/register.html
  src/main/resources/templates/members/edit.html
  src/main/resources/templates/members/login-form.html
  src/main/resources/templates/members/register.html
Labels: 🛠리팩토링, 🎆스타일

#166 refactor: 질문 검색 기준을 1개로 통합
  src/main/java/shop/tryit/domain/question/QuestionSearchCondition.java
  src/main/java/shop/tryit/repository/question/QuestionCustomImpl.java
  src/main/resources/templates/questions/list.html
Labels: 🛠리팩토링, 📰게시판

#171 feat: 장바구니 관련 등록 기능 개발
  src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
  src/main/java/shop/tryit/domain/cart/repository/CartRepository.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/domain/cart/service/CartService.java
  src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
  src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
  src/main/java/shop/tryit/repository/cart/CartJpaRepository.java
  src/main/java/shop/tryit/repository/cart/CartRepositoryImpl.java
  src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
  src/test/java/shop/tryit/domain/cart/CartServiceTests.java
Labels: ✒️기능개발, 🛒장바구니

#174 feat: 장바구니 생성 서비스 로직 개발
  src/main/java/shop/tryit/domain/cart/repository/CartRepository.java
  src/main/java/shop/tryit/domain/cart/service/CartService.java
  src/main/java/shop/tryit/repository/cart/CartJpaRepository.java
  src/main/java/shop/tryit/repository/cart/CartRepositoryImpl.java
  src/test/java/shop/tryit/domain/cart/CartServiceTests.java
Labels: 🛠리팩토링, ✒️기능개발, 🛒장바구니

#175 feat: 장바구니 상품 추가 서비스 로직 개발
  src/main/java/shop/tryit/domain/cart/entity/CartItem.java
  src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
  src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
  src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
Labels: 🛠리팩토링, ✒️기능개발, 🛒장바구니

#176 feat: 결제 정보 저장 기능 구현
  src/main/java/shop/tryit/domain/payment/Payment.java
  src/main/java/shop/tryit/domain/payment/PaymentRepository.java
  src/main/java/shop/tryit/domain/payment/PaymentService.java
  src/main/java/shop/tryit/repository/payment/PaymentJpaRepository.java
  src/main/java/shop/tryit/repository/payment/PaymentRepositoryImpl.java
  src/test/java/shop/tryit/domain/payment/PaymentServiceTests.java
Labels: ✒️기능개발, 💰결제

#179 feat: 장바구니 조회 서비스 로직 개발
  src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
  src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
  src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
Labels: ✒️기능개발, 🛒장바구니

#184 feat: 장바구니 상품 수정 기능 개발
  src/main/java/shop/tryit/domain/cart/entity/CartItem.java
  src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
  src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
Labels: ✒️기능개발, 🎆스타일, 🛒장바구니

#185 feat: 주문, 주문상품 엔티티에 equals, hashcode 오버라이딩
  src/main/java/shop/tryit/domain/order/Order.java
  src/main/java/shop/tryit/domain/order/OrderDetail.java
Labels: ✒️기능개발, 📞주문

#188 feat: 결제 웹 계층 구현
  src/main/java/shop/tryit/web/payment/PayController.java
  src/main/java/shop/tryit/web/payment/PaymentAdapter.java
  src/main/java/shop/tryit/web/payment/PaymentDto.java
  src/main/resources/static/img/payment_icon_yellow_small.png
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/payment/payment-form.html
Labels: ✒️기능개발, 🖼디자인, 💰결제

#187 feat: 장바구니 상품 삭제 기능 개발
  src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
  src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
Labels: ✒️기능개발, 🛒장바구니

#182 feat: 상품 리포지토리에서 주문 상품 조회
  src/main/java/shop/tryit/domain/item/ItemRepository.java
  src/main/java/shop/tryit/repository/item/ItemCustom.java
  src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
  src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
  src/test/java/shop/tryit/domain/item/ItemRepositoryTests.java
Labels: ✒️기능개발, 🎁상품

#193 feat: 상품 상세에서 단건 주문 시 결제 컨트롤러로 정보 전달
  src/main/java/shop/tryit/web/item/ItemController.java
  src/main/java/shop/tryit/web/payment/PaymentController.java
  src/main/java/shop/tryit/web/payment/PaymentFormDto.java
  src/main/resources/templates/items/detail.html
Labels: ✒️기능개발, 🎁상품, 🎆스타일, 💰결제

#195 feat: 주문 기준으로 주문 상세 조회 기능 구현
  src/main/java/shop/tryit/domain/order/OrderDetail.java
  src/main/java/shop/tryit/domain/order/OrderDetailRepository.java
  src/main/java/shop/tryit/domain/order/OrderDetailSearchDto.java
  src/main/java/shop/tryit/domain/order/OrderSearchDto.java
  src/main/java/shop/tryit/repository/order/OrderDetailCustom.java
  src/main/java/shop/tryit/repository/order/OrderDetailCustomImpl.java
  src/main/java/shop/tryit/repository/order/OrderDetailJpaRepository.java
  src/main/java/shop/tryit/repository/order/OrderDetailRepositoryImpl.java
Labels: ✒️기능개발, 📞주문

#199 refactor: 주문 어댑터의 엔티티 변환 파라미터 수정
  src/main/java/shop/tryit/web/order/OrderController.java
Labels: 🛠리팩토링, 📞주문

#200 build: editorconfig에 자바스크립트 코드 정렬 추가
  .editorconfig
Labels: ⚙세팅

#202 refactor: 주문 dto에 주소지 추가
  src/main/java/shop/tryit/domain/order/OrderSearchDto.java
  src/main/java/shop/tryit/repository/order/OrderCustomImpl.java
Labels: 🛠리팩토링, 📞주문

#203 refactor: 결제 웹 계층 리팩토링(단건 주문결제)
  src/main/java/shop/tryit/domain/member/Member.java
  src/main/java/shop/tryit/domain/payment/Payment.java
  src/main/java/shop/tryit/domain/payment/PaymentRepository.java
  src/main/java/shop/tryit/repository/payment/PaymentJpaRepository.java
  src/main/java/shop/tryit/repository/payment/PaymentRepositoryImpl.java
  src/main/java/shop/tryit/web/payment/PaymentAdapter.java
  src/main/java/shop/tryit/web/payment/PaymentController.java
  src/main/java/shop/tryit/web/payment/PaymentDto.java
  src/main/java/shop/tryit/web/payment/PaymentRequsetDto.java
  src/main/java/shop/tryit/web/payment/PaymentResponseDto.java
  src/main/resources/templates/payment/payment-form.html
Labels: 🛠리팩토링, 💰결제

#206 feat: 장바구니 웹 계층 개발 (상품 담기)
  src/main/java/shop/tryit/domain/cart/entity/CartItem.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/domain/cart/service/CartService.java
  src/main/java/shop/tryit/web/cart/controller/CartController.java
  src/main/java/shop/tryit/web/cart/dto/CartItemAdapter.java
  src/main/java/shop/tryit/web/cart/dto/CartItemDto.java
  src/main/resources/templates/items/detail.html
  src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
  src/test/java/shop/tryit/domain/cart/CartServiceTests.java
Labels: 🛠리팩토링, ✒️기능개발, 🎁상품, 🖼디자인, 🛒장바구니

#208 feat: 주문 페이징 기능 구현
  src/main/java/shop/tryit/domain/order/OrderService.java
  src/main/java/shop/tryit/repository/order/OrderCustomImpl.java
  src/main/java/shop/tryit/web/order/OrderController.java
  src/main/resources/templates/orders/list.html
Labels: ✒️기능개발, 📞주문

#209 feat: 장바구니 웹 계층 개발 (조회)
  src/main/java/shop/tryit/domain/cart/entity/CartItem.java
  src/main/java/shop/tryit/web/cart/controller/CartController.java
  src/main/java/shop/tryit/web/cart/dto/CartItemAdapter.java
  src/main/java/shop/tryit/web/cart/dto/CartListDto.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/cart/list.html
Labels: 🛠리팩토링, ✒️기능개발, 🖼디자인, 🎆스타일, 🛒장바구니

#211 refactor: 장바구니 URI 변경
  src/main/java/shop/tryit/web/cart/controller/CartController.java
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/items/detail.html
Labels: 🛠리팩토링, 🛒장바구니

#216 feat: 주문 폼에서 주문 컨트롤러로 데이터 전달 js 로직 구현
  src/main/resources/templates/payment/payment-form.html
Labels: ✒️기능개발, 🎆스타일, 💰결제

#220 refactor: 장바구니 퍼사드 패턴 적용
  src/main/java/shop/tryit/domain/cart/dto/CartItemDto.java
  src/main/java/shop/tryit/domain/cart/dto/CartListDto.java
  src/main/java/shop/tryit/domain/cart/service/CartFacade.java
  src/main/java/shop/tryit/web/cart/CartController.java
  src/main/java/shop/tryit/web/cart/dto/CartItemAdapter.java
Labels: 🛠리팩토링, 🛒장바구니

#222 refactor: 상품 퍼사드 패턴 적용
  src/main/java/shop/tryit/domain/item/ImageService.java
  src/main/java/shop/tryit/domain/item/ItemPacade.java
  src/main/java/shop/tryit/domain/item/dto/ItemDto.java
  src/main/java/shop/tryit/domain/item/dto/ItemFormDto.java
  src/main/java/shop/tryit/web/item/ItemAdapter.java
  src/main/java/shop/tryit/web/item/ItemController.java
Labels: 🛠리팩토링, 🎁상품

#219 refactor: 회원 퍼사드 패턴 적용
  src/main/java/shop/tryit/domain/member/MemberFacade.java
  src/main/java/shop/tryit/domain/member/dto/MemberFormDto.java
  src/main/java/shop/tryit/web/member/AddressAdapter.java
  src/main/java/shop/tryit/web/member/MemberAdapter.java
  src/main/java/shop/tryit/web/member/MemberController.java
Labels: 🛠리팩토링, ✒️기능개발, 😊회원

#223 refactor: 결제 퍼사드 패턴 적용
  src/main/java/shop/tryit/domain/payment/PaymentFacade.java
  src/main/java/shop/tryit/domain/payment/dto/PaymentDto.java
  src/main/java/shop/tryit/domain/payment/dto/PaymentRequsetDto.java
  src/main/java/shop/tryit/domain/payment/dto/PaymentResponseDto.java
  src/main/java/shop/tryit/domain/payment/dto/PaymentSaveDto.java
  src/main/java/shop/tryit/web/payment/PaymentAdapter.java
  src/main/java/shop/tryit/web/payment/PaymentController.java
Labels: 🛠리팩토링, ✒️기능개발, 💰결제

#228 refactor: 결제 서비스 테스트 수정
  src/test/java/shop/tryit/domain/payment/PaymentServiceTests.java
Labels: 🛠리팩토링, 💰결제

#225 refactor: QnA에 퍼사드 패턴 적용
  src/main/java/shop/tryit/domain/answer/Answer.java
  src/main/java/shop/tryit/domain/answer/AnswerRepository.java
  src/main/java/shop/tryit/domain/answer/dto/AnswerFormDto.java
  src/main/java/shop/tryit/domain/answer/service/AnswerService.java
  src/main/java/shop/tryit/domain/question/QuestionRepository.java
  src/main/java/shop/tryit/domain/question/dto/QuestionCheckPasswordFormDto.java
  src/main/java/shop/tryit/domain/question/dto/QuestionFormDto.java
  src/main/java/shop/tryit/domain/question/dto/QuestionSaveFormDto.java
  src/main/java/shop/tryit/domain/question/dto/QuestionSearchCondition.java
  src/main/java/shop/tryit/domain/question/dto/QuestionSearchDto.java
  src/main/java/shop/tryit/domain/question/entity/Question.java
  src/main/java/shop/tryit/domain/question/service/QnAFacade.java
  src/main/java/shop/tryit/domain/question/service/QuestionService.java
  src/main/java/shop/tryit/repository/answer/AnswerJpaRepository.java
  src/main/java/shop/tryit/repository/answer/AnswerRepositoryImpl.java
  src/main/java/shop/tryit/repository/question/QuestionCustom.java
  src/main/java/shop/tryit/repository/question/QuestionCustomImpl.java
  src/main/java/shop/tryit/repository/question/QuestionJpaRepository.java
  src/main/java/shop/tryit/repository/question/QuestionRepositoryImpl.java
  src/main/java/shop/tryit/web/answer/AnswerAdapter.java
  src/main/java/shop/tryit/web/answer/AnswerController.java
  src/main/java/shop/tryit/web/question/QuestionAdapter.java
  src/main/java/shop/tryit/web/question/QuestionController.java
  src/test/java/shop/tryit/domain/answer/AnswerServiceTests.java
  src/test/java/shop/tryit/domain/question/QuestionServiceTests.java
  src/test/java/shop/tryit/repository/question/QuestionRepositoryImplTests.java
Labels: 🛠리팩토링, 📰게시판

#230 refactor : 주문에 퍼사드 패턴 적용
  src/main/java/shop/tryit/domain/order/OrderDetailRepository.java
  src/main/java/shop/tryit/domain/order/OrderRepository.java
  src/main/java/shop/tryit/domain/order/dto/OrderDetailSearchDto.java
  src/main/java/shop/tryit/domain/order/dto/OrderDto.java
  src/main/java/shop/tryit/domain/order/dto/OrderFormDto.java
  src/main/java/shop/tryit/domain/order/dto/OrderSearchDto.java
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
  src/main/java/shop/tryit/domain/order/service/OrderService.java
  src/main/java/shop/tryit/repository/order/OrderCustom.java
  src/main/java/shop/tryit/repository/order/OrderCustomImpl.java
  src/main/java/shop/tryit/repository/order/OrderDetailCustom.java
  src/main/java/shop/tryit/repository/order/OrderDetailCustomImpl.java
  src/main/java/shop/tryit/repository/order/OrderDetailRepositoryImpl.java
  src/main/java/shop/tryit/repository/order/OrderRepositoryImpl.java
  src/main/java/shop/tryit/web/order/OrderAdapter.java
  src/main/java/shop/tryit/web/order/OrderController.java
  src/test/java/shop/tryit/domain/order/OrderServiceTests.java
Labels: 🛠리팩토링, 📞주문

#231 refactor: 상품 도메인 계층 패키지 변경
  src/main/java/shop/tryit/domain/cart/dto/CartListDto.java
  src/main/java/shop/tryit/domain/cart/entity/CartItem.java
  src/main/java/shop/tryit/domain/cart/repository/CartItemRepository.java
  src/main/java/shop/tryit/domain/cart/service/CartFacade.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/domain/item/dto/ItemDto.java
  src/main/java/shop/tryit/domain/item/dto/ItemSearchDto.java
  src/main/java/shop/tryit/domain/item/entity/Image.java
  src/main/java/shop/tryit/domain/item/entity/Item.java
  src/main/java/shop/tryit/domain/item/exception/NotEnoughStockException.java
  src/main/java/shop/tryit/domain/item/repository/ItemRepository.java
  src/main/java/shop/tryit/domain/item/service/ImageService.java
  src/main/java/shop/tryit/domain/item/service/ImageStore.java
  src/main/java/shop/tryit/domain/item/service/ItemPacade.java
  src/main/java/shop/tryit/domain/item/service/ItemService.java
  src/main/java/shop/tryit/domain/order/OrderDetail.java
  src/main/java/shop/tryit/domain/order/dto/OrderDetailSearchDto.java
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
  src/main/java/shop/tryit/domain/order/service/OrderService.java
  src/main/java/shop/tryit/domain/payment/PaymentFacade.java
  src/main/java/shop/tryit/domain/payment/dto/PaymentResponseDto.java
  src/main/java/shop/tryit/repository/cart/CartItemJpaRepository.java
  src/main/java/shop/tryit/repository/cart/CartItemRepositoryImpl.java
  src/main/java/shop/tryit/repository/item/ItemCustom.java
  src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
  src/main/java/shop/tryit/repository/item/ItemJpaRepository.java
  src/main/java/shop/tryit/repository/item/ItemRepositoryImpl.java
  src/main/java/shop/tryit/repository/order/OrderDetailCustomImpl.java
  src/main/java/shop/tryit/web/cart/CartController.java
  src/main/java/shop/tryit/web/item/ImageController.java
  src/main/java/shop/tryit/web/item/ItemController.java
  src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
  src/test/java/shop/tryit/domain/item/ItemRepositoryTests.java
  src/test/java/shop/tryit/domain/item/ItemServiceTests.java
  src/test/java/shop/tryit/domain/order/OrderServiceTests.java
Labels: 🛠리팩토링, 🎁상품

#233 refactor: 상품 도메인 계층 패키지 변경 추가
  src/main/java/shop/tryit/repository/item/ItemCustomImpl.java
Labels: 🛠리팩토링, 🎁상품

#235 refactor: CartFacade에 @Transactional 추가
  src/main/java/shop/tryit/domain/cart/service/CartFacade.java
Labels: 🛠리팩토링, 🛒장바구니

#238 refactor: PaymentFacade에 @Transactional 추가
  src/main/java/shop/tryit/domain/payment/PaymentFacade.java
Labels: 🛠리팩토링, 💰결제

#240 refactor: OrderFacade, QnaFacade에 @Transactional 추가
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
  src/main/java/shop/tryit/domain/question/service/QnAFacade.java
  src/main/java/shop/tryit/repository/order/OrderCustomImpl.java
  src/main/java/shop/tryit/repository/question/QuestionCustomImpl.java
Labels: 🛠리팩토링, 📞주문

#244 refactor: css 파일 분리
  src/main/resources/static/css/cart.css
  src/main/resources/static/css/common.css
  src/main/resources/static/css/item.css
  src/main/resources/static/css/style.css
  src/main/resources/templates/cart/list.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/items/detail.html
  src/main/resources/templates/items/list.html
  src/main/resources/templates/items/register.html
  src/main/resources/templates/items/update.html
Labels: 🛠리팩토링, 🖼디자인

#245 refactor: 공지에 퍼사드 패턴 적용
  src/main/java/shop/tryit/domain/notice/NoticeRepository.java
  src/main/java/shop/tryit/domain/notice/dto/NoticeSaveFormDto.java
  src/main/java/shop/tryit/domain/notice/dto/NoticeSearchFormDto.java
  src/main/java/shop/tryit/domain/notice/dto/NoticeUpdateFormDto.java
  src/main/java/shop/tryit/domain/notice/dto/NoticeViewFormDto.java
  src/main/java/shop/tryit/domain/notice/entity/Notice.java
  src/main/java/shop/tryit/domain/notice/service/NoticeFacade.java
  src/main/java/shop/tryit/domain/notice/service/NoticeService.java
  src/main/java/shop/tryit/repository/notice/NoticeJpaRepository.java
  src/main/java/shop/tryit/repository/notice/NoticeRepositoryImpl.java
  src/main/java/shop/tryit/web/notice/NoticeAdapter.java
  src/main/java/shop/tryit/web/notice/NoticeController.java
  src/test/java/shop/tryit/domain/notice/NoticeServiceTests.java
Labels: 🛠리팩토링, 📰게시판

#249 refactor: 장바구니 관련 리팩토링
  src/main/java/shop/tryit/domain/cart/entity/CartItem.java
  src/main/java/shop/tryit/domain/cart/service/CartFacade.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/domain/item/entity/Item.java
  src/main/java/shop/tryit/web/cart/CartController.java
Labels: 🛠리팩토링, 🛒장바구니

#247 refactor: 답변 어댑터 삭제
  src/main/java/shop/tryit/web/answer/AnswerAdapter.java
Labels: 🛠리팩토링, 📋공지사항

#255 refactor: 트랜잭션을 QnA 서비스가 아닌 퍼사드에 적용
  src/main/java/shop/tryit/domain/answer/service/AnswerService.java
  src/main/java/shop/tryit/domain/question/service/QnAFacade.java
  src/main/java/shop/tryit/domain/question/service/QuestionService.java
Labels: 🛠리팩토링, 📰게시판

#252 refactor: 주문 상세 등록시 상품 재고 감소 기능 추가
  src/main/java/shop/tryit/domain/order/OrderDetail.java
  src/main/java/shop/tryit/domain/order/service/OrderDetailService.java
Labels: 🛠리팩토링, 📞주문

#254 feat: 장바구니 목록에서 checkbox 처리 및 주문 상품 데이터 전달
  src/main/resources/static/css/cart.css
  src/main/resources/templates/cart/list.html
Labels: 🛠리팩토링, ✒️기능개발, 🛒장바구니

#261 refactor: 주문 목록 기능의 파라미터 수정
  src/main/java/shop/tryit/domain/order/service/OrderFacade.java
  src/main/java/shop/tryit/domain/order/service/OrderService.java
Labels: 🛠리팩토링, 📞주문

#265 feat: 결제 웹 계층 기능 추가 및 변경
  src/main/java/shop/tryit/domain/order/dto/OrderDetailDto.java
  src/main/java/shop/tryit/domain/payment/PaymentFacade.java
  src/main/java/shop/tryit/web/order/OrderController.java
  src/main/java/shop/tryit/web/payment/PaymentController.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/payment/payment-form.html
Labels: 🛠리팩토링, ✒️기능개발, 📞주문, 🖼디자인, 🎆스타일, 💰결제

#266 feat: 장바구니 목록에서 수량 변경 처리
  src/main/java/shop/tryit/domain/cart/dto/CartListDto.java
  src/main/java/shop/tryit/domain/cart/service/CartFacade.java
  src/main/java/shop/tryit/domain/cart/service/CartItemService.java
  src/main/java/shop/tryit/web/cart/CartController.java
  src/main/resources/templates/carts/list.html
  src/test/java/shop/tryit/domain/cart/CartItemServiceTests.java
Labels: ✒️기능개발, 🛒장바구니

#268 refactor: 장바구니 목록 폼 js 리팩토링
  src/main/java/shop/tryit/domain/cart/dto/CartListDto.java
  src/main/resources/templates/carts/list.html
  src/main/resources/templates/items/detail.html
Labels: 🛠리팩토링, 🎆스타일, 🛒장바구니

#270 refactor: 장바구니 상품 담기 컨트롤러에서 반환하는 성공 응답코드 변경
  src/main/java/shop/tryit/web/cart/CartController.java
Labels: 🛠리팩토링, 🛒장바구니

#272 feat: 장바구니 목록에서 삭제 버튼 처리
  src/main/java/shop/tryit/domain/cart/service/CartFacade.java
  src/main/java/shop/tryit/web/cart/CartController.java
  src/main/resources/templates/carts/list.html
Labels: ✒️기능개발, 🛒장바구니
